name: Tyler Burba
favicon: null
layout_spectrum: 0.12811937252990901
typography_spectrum: 0.9295576470904052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8248224488925189
  lightness: 0.6493100738152862
  saturation: 0.23665608069859445
  rhythmicContrast: 0.9521682257764041
purpose: []
